on: workflow_dispatch

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::tidync
            any::usethis

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set git user id
        run: |
          git config --local user.email "claire.davies@csiro.au"
          git config --local user.name "clairedavies"    
          
      - name: Import data
        run: Rscript -e 'source("data-raw/All_RData.R")'

      - name: Commit results
          git add R/sysdata.rda
          git commit -m 'Data updated' || echo "No changes to commit"
          git push --force   || echo "No changes to commit"


