# on: workflow_dispatch # Claires original one. Want to try this first

on:
  push:
    branches: main
  pull_request:
    branches: main

name: Update Data

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::tidync
            any::usethis

      - name: Check out repository
        uses: actions/checkout@v4        
        with:
          persist-credentials: false
      
      - name: Import data
        run: Rscript -e 'source("data-raw/All_RData.R")'
        
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_timestamp: true
          commit_prefix: "[AUTO-COMMIT]"
          commit_message: "Data Updated"

      # - name: Auto-merge Pull Request (Use with caution!)
      #   uses: pascalgn/automerge-action@v0.15.6  # Replace with the latest version if needed
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a secret token with appropriate permissions


      # - name: create pull request
      #   run: gh pr create -B main --title 'Update Data'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 
      